public class ArithmeticException extends Throwable {
    public static void main(String[] args){
        int a = 3;
        int b = 0;

        try {
            System.out.println( a / b );
        }
        catch (java.lang.ArithmeticException e){
            System.out.println( e );

        }
        System.out.println("code after exception");

    }
}
